# Generated by Django 5.2.4 on 2025-07-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='room_code',
            field=models.CharField(default='e71021f0', max_length=8, unique=True),
        ),
    ]
