# Generated by Django 5.2.4 on 2025-07-23 01:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='room_code',
            field=models.CharField(default=uuid.UUID('bf735651-990d-4928-80b3-68c91a8a1bd3'), max_length=8, unique=True),
        ),
    ]
