# Generated by Django 5.2.4 on 2025-07-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_room_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='room_code',
        ),
    ]
