# Generated by Django 5.2.4 on 2025-07-29 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_remove_board_room_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoardData',
            new_name='Nodedata',
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('type', models.CharField(default='default', max_length=50)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='board.board')),
            ],
        ),
    ]
