# Generated by Django 5.2.4 on 2025-07-30 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_rename_boarddata_nodedata_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='node_id',
        ),
    ]
