# Generated by Django 5.2.4 on 2025-08-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_edge'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
