# Generated by Django 5.2.4 on 2025-08-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_node_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='color',
            field=models.CharField(blank=True, default='#eff6ff', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='opacity',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
