# Generated by Django 5.2.4 on 2025-08-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_node_color_node_opacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
