# Generated by Django 5.2.4 on 2025-08-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_node_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
