# Generated by Django 5.2.4 on 2025-08-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_alter_node_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
