# Generated by Django 5.2.4 on 2025-08-15 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_alter_node_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveBoardUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_users', to='board.board')),
            ],
        ),
    ]
