# Generated by Django 5.2.4 on 2025-08-16 01:29

import board.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_activeboarduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeboarduser',
            name='color',
            field=models.CharField(default=board.utils.random_color, max_length=7),
        ),
    ]
